import { PrismaClient, CategoriaComponente, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

interface ComponenteData {
  tipo: string;
  nombre: string;
  descripcion: string;
  categoria: CategoriaComponente;
  icono: string;
  configSchema: Prisma.InputJsonValue;
  ejemploConfig: Prisma.InputJsonValue;
  implementado: boolean;
  habilitado: boolean;
  orden: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// INTERACTIVO (15 componentes)
// ═══════════════════════════════════════════════════════════════════════════
const INTERACTIVOS: ComponenteData[] = [
  {
    tipo: 'MultipleChoice',
    nombre: 'Opción Múltiple',
    descripcion: 'Pregunta con múltiples opciones y una respuesta correcta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔘',
    configSchema: {},
    ejemploConfig: {
      pregunta: '¿Cuánto es 2 + 2?',
      opciones: ['3', '4', '5'],
      respuestaCorrecta: 1,
    },
    implementado: true,
    habilitado: true,
    orden: 1,
  },
  {
    tipo: 'FillBlanks',
    nombre: 'Completar Espacios',
    descripcion: 'Texto con espacios en blanco para completar',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {
      texto: 'El resultado de {{0}} + {{1}} es {{2}}',
      respuestas: ['2', '3', '5'],
    },
    implementado: true,
    habilitado: true,
    orden: 2,
  },
  {
    tipo: 'VerdaderoFalso',
    nombre: 'Verdadero o Falso',
    descripcion: 'Afirmación para marcar como verdadera o falsa',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '✅',
    configSchema: {},
    ejemploConfig: { afirmacion: 'La Tierra es plana', esVerdadero: false },
    implementado: true,
    habilitado: true,
    orden: 3,
  },
  {
    tipo: 'DragDropZone',
    nombre: 'Arrastrar y Soltar',
    descripcion: 'Zona para arrastrar elementos a destinos específicos',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 4,
  },
  {
    tipo: 'MatchingPairs',
    nombre: 'Emparejar',
    descripcion: 'Conectar elementos que corresponden entre sí',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔗',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 5,
  },
  {
    tipo: 'OrderSequence',
    nombre: 'Ordenar Secuencia',
    descripcion: 'Ordenar elementos en la secuencia correcta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 6,
  },
  {
    tipo: 'Hotspot',
    nombre: 'Hotspot',
    descripcion: 'Clickear zonas específicas de una imagen',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📍',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 7,
  },
  {
    tipo: 'Slider',
    nombre: 'Slider',
    descripcion: 'Seleccionar un valor deslizando',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🎚️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 8,
  },
  {
    tipo: 'TextInput',
    nombre: 'Campo de Texto',
    descripcion: 'Input de texto corto',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '✏️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 9,
  },
  {
    tipo: 'TextArea',
    nombre: 'Área de Texto',
    descripcion: 'Input de texto largo multilínea',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📄',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 10,
  },
  {
    tipo: 'MultipleSelect',
    nombre: 'Selección Múltiple',
    descripcion: 'Seleccionar varias opciones correctas',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '☑️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 11,
  },
  {
    tipo: 'Sorting',
    nombre: 'Clasificar',
    descripcion: 'Clasificar elementos en categorías',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🗂️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 12,
  },
  {
    tipo: 'NumberInput',
    nombre: 'Input Numérico',
    descripcion: 'Ingresar un número como respuesta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔢',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 13,
  },
  {
    tipo: 'Rating',
    nombre: 'Valoración',
    descripcion: 'Calificar con estrellas o puntos',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '⭐',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 14,
  },
  {
    tipo: 'ClickReveal',
    nombre: 'Click para Revelar',
    descripcion: 'Contenido oculto que se revela al hacer click',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '👆',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 15,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CONTENIDO (15 componentes)
// ═══════════════════════════════════════════════════════════════════════════
const CONTENIDO: ComponenteData[] = [
  {
    tipo: 'VideoPlayer',
    nombre: 'Reproductor de Video',
    descripcion: 'Reproducir video con controles',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '▶️',
    configSchema: {},
    ejemploConfig: {
      url: 'https://youtube.com/watch?v=ejemplo',
      titulo: 'Video de ejemplo',
    },
    implementado: true,
    habilitado: true,
    orden: 16,
  },
  {
    tipo: 'TextBlock',
    nombre: 'Bloque de Texto',
    descripcion: 'Texto enriquecido con formato',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 17,
  },
  {
    tipo: 'ImageDisplay',
    nombre: 'Imagen',
    descripcion: 'Mostrar una imagen con descripción',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '🖼️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 18,
  },
  {
    tipo: 'VideoEmbed',
    nombre: 'Video Embebido',
    descripcion: 'Embeber video de YouTube, Vimeo, etc.',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📺',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 19,
  },
  {
    tipo: 'CodeSnippet',
    nombre: 'Código',
    descripcion: 'Mostrar código con resaltado de sintaxis',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '💻',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 20,
  },
  {
    tipo: 'AudioPlayer',
    nombre: 'Reproductor de Audio',
    descripcion: 'Reproducir archivo de audio',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '🎵',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 21,
  },
  {
    tipo: 'Divider',
    nombre: 'Separador',
    descripcion: 'Línea divisoria entre secciones',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '➖',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 22,
  },
  {
    tipo: 'CalloutBox',
    nombre: 'Callout',
    descripcion: 'Caja destacada de información importante',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '💡',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 23,
  },
  {
    tipo: 'Quote',
    nombre: 'Cita',
    descripcion: 'Cita o bloque destacado de texto',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '💬',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 24,
  },
  {
    tipo: 'Accordion',
    nombre: 'Acordeón',
    descripcion: 'Secciones expandibles/colapsables',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📂',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 25,
  },
  {
    tipo: 'Tabs',
    nombre: 'Pestañas',
    descripcion: 'Contenido organizado en pestañas',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📑',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 26,
  },
  {
    tipo: 'Table',
    nombre: 'Tabla',
    descripcion: 'Tabla de datos',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📊',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 27,
  },
  {
    tipo: 'List',
    nombre: 'Lista',
    descripcion: 'Lista ordenada o desordenada',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 28,
  },
  {
    tipo: 'Definition',
    nombre: 'Definición',
    descripcion: 'Término con su definición',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📖',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 29,
  },
  {
    tipo: 'Timeline',
    nombre: 'Línea de Tiempo',
    descripcion: 'Eventos ordenados cronológicamente',
    categoria: CategoriaComponente.CONTENIDO,
    icono: '📅',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 30,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// EDITOR_CODIGO (8 componentes)
// ═══════════════════════════════════════════════════════════════════════════
const EDITOR_CODIGO: ComponenteData[] = [
  {
    tipo: 'ScratchJr',
    nombre: 'Scratch Jr',
    descripcion: 'Programación visual con bloques para niños',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🧩',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 31,
  },
  {
    tipo: 'Blockly',
    nombre: 'Blockly',
    descripcion: 'Programación visual con bloques avanzados',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🔧',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 32,
  },
  {
    tipo: 'PythonConsole',
    nombre: 'Consola Python',
    descripcion: 'Consola interactiva de Python',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🐍',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 33,
  },
  {
    tipo: 'PythonTurtle',
    nombre: 'Python Turtle',
    descripcion: 'Programación visual con tortuga gráfica',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🐢',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 34,
  },
  {
    tipo: 'HTMLPreview',
    nombre: 'Preview HTML',
    descripcion: 'Editor HTML con preview en vivo',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🌐',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 35,
  },
  {
    tipo: 'LuauEditor',
    nombre: 'Editor Luau',
    descripcion: 'Editor de código Luau para Roblox',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🎮',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 36,
  },
  {
    tipo: 'JavaScriptConsole',
    nombre: 'Consola JavaScript',
    descripcion: 'Consola interactiva de JavaScript',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '⚡',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 37,
  },
  {
    tipo: 'SQLEditor',
    nombre: 'Editor SQL',
    descripcion: 'Editor de consultas SQL',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🗄️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 38,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// MULTIMEDIA (8 componentes)
// ═══════════════════════════════════════════════════════════════════════════
const MULTIMEDIA: ComponenteData[] = [
  {
    tipo: 'ImageGallery',
    nombre: 'Galería de Imágenes',
    descripcion: 'Carrusel o grilla de imágenes',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎞️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 39,
  },
  {
    tipo: 'AudioRecorder',
    nombre: 'Grabador de Audio',
    descripcion: 'Grabar audio desde el micrófono',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎙️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 40,
  },
  {
    tipo: 'DrawingCanvas',
    nombre: 'Canvas de Dibujo',
    descripcion: 'Lienzo para dibujar libremente',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎨',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 41,
  },
  {
    tipo: 'ImageAnnotation',
    nombre: 'Anotación de Imagen',
    descripcion: 'Marcar y anotar sobre una imagen',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '✍️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 42,
  },
  {
    tipo: 'VideoRecorder',
    nombre: 'Grabador de Video',
    descripcion: 'Grabar video desde la cámara',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '📹',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 43,
  },
  {
    tipo: 'Whiteboard',
    nombre: 'Pizarra',
    descripcion: 'Pizarra colaborativa',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 44,
  },
  {
    tipo: 'MusicMaker',
    nombre: 'Creador de Música',
    descripcion: 'Crear melodías simples',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎹',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 45,
  },
  {
    tipo: 'VoiceRecorder',
    nombre: 'Grabador de Voz',
    descripcion: 'Grabar respuestas de voz',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🗣️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 46,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// GAMIFICACION (8 componentes)
// ═══════════════════════════════════════════════════════════════════════════
const GAMIFICACION: ComponenteData[] = [
  {
    tipo: 'ProgressBar',
    nombre: 'Barra de Progreso',
    descripcion: 'Mostrar progreso de avance',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '📊',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 47,
  },
  {
    tipo: 'XPCounter',
    nombre: 'Contador XP',
    descripcion: 'Mostrar puntos de experiencia',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '✨',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 48,
  },
  {
    tipo: 'BadgeDisplay',
    nombre: 'Mostrar Insignia',
    descripcion: 'Mostrar insignia obtenida',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '🏅',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 49,
  },
  {
    tipo: 'AchievementUnlock',
    nombre: 'Desbloqueo de Logro',
    descripcion: 'Animación al desbloquear un logro',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '🏆',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 50,
  },
  {
    tipo: 'StreakCounter',
    nombre: 'Contador de Racha',
    descripcion: 'Mostrar días consecutivos',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '🔥',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 51,
  },
  {
    tipo: 'LeaderboardMini',
    nombre: 'Mini Ranking',
    descripcion: 'Tabla de posiciones reducida',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '🥇',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 52,
  },
  {
    tipo: 'Timer',
    nombre: 'Temporizador',
    descripcion: 'Cuenta regresiva o cronómetro',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '⏱️',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 53,
  },
  {
    tipo: 'ScoreDisplay',
    nombre: 'Mostrar Puntaje',
    descripcion: 'Visualización de puntaje actual',
    categoria: CategoriaComponente.GAMIFICACION,
    icono: '💯',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 54,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// EVALUACION (8 componentes)
// ═══════════════════════════════════════════════════════════════════════════
const EVALUACION: ComponenteData[] = [
  {
    tipo: 'Quiz',
    nombre: 'Quiz',
    descripcion: 'Conjunto de preguntas evaluativas',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 55,
  },
  {
    tipo: 'PracticeMode',
    nombre: 'Modo Práctica',
    descripcion: 'Ejercicios sin puntuación',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 56,
  },
  {
    tipo: 'Checkpoint',
    nombre: 'Checkpoint',
    descripcion: 'Punto de verificación de conocimientos',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🚩',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 57,
  },
  {
    tipo: 'TimedChallenge',
    nombre: 'Desafío Cronometrado',
    descripcion: 'Ejercicio con límite de tiempo',
    categoria: CategoriaComponente.EVALUACION,
    icono: '⏰',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 58,
  },
  {
    tipo: 'SelfAssessment',
    nombre: 'Autoevaluación',
    descripcion: 'El estudiante evalúa su propio trabajo',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🪞',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 59,
  },
  {
    tipo: 'PeerReview',
    nombre: 'Revisión de Pares',
    descripcion: 'Evaluación entre estudiantes',
    categoria: CategoriaComponente.EVALUACION,
    icono: '👥',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 60,
  },
  {
    tipo: 'Rubric',
    nombre: 'Rúbrica',
    descripcion: 'Criterios de evaluación detallados',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 61,
  },
  {
    tipo: 'Certificate',
    nombre: 'Certificado',
    descripcion: 'Certificado de finalización',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📜',
    configSchema: {},
    ejemploConfig: {},
    implementado: false,
    habilitado: false,
    orden: 62,
  },
];

// Todos los componentes
const TODOS_COMPONENTES: ComponenteData[] = [
  ...INTERACTIVOS,
  ...CONTENIDO,
  ...EDITOR_CODIGO,
  ...MULTIMEDIA,
  ...GAMIFICACION,
  ...EVALUACION,
];

export async function seedComponentesCatalogo(): Promise<void> {
  console.log('🌱 Seeding ComponenteCatalogo...');

  for (const comp of TODOS_COMPONENTES) {
    await prisma.componenteCatalogo.upsert({
      where: { tipo: comp.tipo },
      update: comp,
      create: comp,
    });
  }

  // Estadísticas
  const implementados = TODOS_COMPONENTES.filter((c) => c.implementado).length;
  const pendientes = TODOS_COMPONENTES.filter((c) => !c.implementado).length;

  console.log(`✅ Seed completado:`);
  console.log(`   - Total: ${TODOS_COMPONENTES.length} componentes`);
  console.log(`   - Implementados: ${implementados}`);
  console.log(`   - Pendientes: ${pendientes}`);
}

// Ejecutar si se llama directamente
seedComponentesCatalogo()
  .catch((e) => {
    console.error('❌ Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
