import { PrismaClient, CategoriaComponente, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

interface ComponenteData {
  tipo: string;
  nombre: string;
  descripcion: string;
  categoria: CategoriaComponente;
  icono: string;
  configSchema: Prisma.InputJsonValue;
  ejemploConfig: Prisma.InputJsonValue;
  implementado: boolean;
  habilitado: boolean;
  orden: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 1: INTERACTIVOS BÁSICOS (15 componentes)
// Los fundamentales. Están en casi todas las actividades.
// ═══════════════════════════════════════════════════════════════════════════
const INTERACTIVOS: ComponenteData[] = [
  {
    tipo: 'DragAndDrop',
    nombre: 'Arrastrar y Soltar',
    descripcion: 'Arrastrar elementos a zonas objetivo con verificación',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Arrastra cada número a su categoría correcta',
      elementos: [
        { id: 'e1', contenido: '2', tipo: 'texto', zonaCorrecta: 'pares' },
        { id: 'e2', contenido: '3', tipo: 'texto', zonaCorrecta: 'impares' },
      ],
      zonas: [
        { id: 'pares', etiqueta: 'Números Pares', aceptaMultiples: true },
        { id: 'impares', etiqueta: 'Números Impares', aceptaMultiples: true },
      ],
      feedback: {
        correcto: '¡Excelente!',
        incorrecto: 'Intenta de nuevo',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 1,
  },
  {
    tipo: 'MatchingPairs',
    nombre: 'Emparejar',
    descripcion: 'Conectar elementos relacionados',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔗',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Conecta cada fórmula con su nombre',
      pares: [
        { id: 'p1', izquierda: 'H₂O', derecha: 'Agua' },
        { id: 'p2', izquierda: 'NaCl', derecha: 'Sal' },
        { id: 'p3', izquierda: 'CO₂', derecha: 'Dióxido de carbono' },
      ],
      feedback: {
        correcto: '¡Excelente! Todas las conexiones son correctas.',
        incorrecto: 'Algunas conexiones no son correctas.',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 2,
  },
  {
    tipo: 'OrderSequence',
    nombre: 'Ordenar Secuencia',
    descripcion: 'Ordenar elementos en secuencia correcta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Ordena los pasos del método científico',
      elementos: [
        { id: 'e1', contenido: 'Observación', ordenCorrecto: 1 },
        { id: 'e2', contenido: 'Hipótesis', ordenCorrecto: 2 },
        { id: 'e3', contenido: 'Experimentación', ordenCorrecto: 3 },
        { id: 'e4', contenido: 'Conclusión', ordenCorrecto: 4 },
      ],
      feedback: {
        correcto: '¡Excelente! El orden es correcto.',
        incorrecto: 'El orden no es correcto. Inténtalo de nuevo.',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 3,
  },
  {
    tipo: 'MultipleChoice',
    nombre: 'Opción Múltiple',
    descripcion: 'Pregunta con múltiples opciones y una respuesta correcta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔘',
    configSchema: {},
    ejemploConfig: {
      pregunta: '¿Cuánto es 2 + 2?',
      opciones: ['3', '4', '5'],
      respuestaCorrecta: 1,
    },
    implementado: true,
    habilitado: true,
    orden: 4,
  },
  {
    tipo: 'FillBlanks',
    nombre: 'Completar Espacios',
    descripcion: 'Texto con espacios en blanco para completar',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {
      texto: 'El resultado de {{0}} + {{1}} es {{2}}',
      respuestas: ['2', '3', '5'],
    },
    implementado: true,
    habilitado: true,
    orden: 5,
  },
  {
    tipo: 'Slider',
    nombre: 'Slider',
    descripcion: 'Ajustar valor en rango con verificación',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🎚️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Ajusta la temperatura para el experimento',
      min: 0,
      max: 100,
      paso: 1,
      valorInicial: 50,
      valorCorrecto: 75,
      tolerancia: 5,
      unidad: '°C',
      feedback: {
        correcto: '¡Perfecto! 75°C es la temperatura ideal.',
        incorrecto: 'No es la temperatura correcta.',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 6,
  },
  {
    tipo: 'ToggleSwitch',
    nombre: 'Interruptor',
    descripcion: 'On/Off para variables con verificación',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔛',
    configSchema: {},
    ejemploConfig: {
      instruccion: '¿Debe activarse el catalizador para esta reacción?',
      label: 'Catalizador',
      valorInicial: false,
      valorCorrecto: true,
      descripcion: 'El catalizador acelera la reacción sin consumirse',
      labelOff: 'Inactivo',
      labelOn: 'Activo',
      feedback: {
        correcto: '¡Correcto! El catalizador debe estar activo.',
        incorrecto: 'No es correcto. Piensa en el efecto del catalizador.',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 7,
  },
  {
    tipo: 'NumberInput',
    nombre: 'Input Numérico',
    descripcion: 'Input numérico con validación de rango y tolerancia',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔢',
    configSchema: {},
    ejemploConfig: {
      instruccion: '¿Cuál es la masa molar del agua (H2O)?',
      label: 'Masa molar',
      min: 0,
      max: 1000,
      valorCorrecto: 18,
      tolerancia: 0.5,
      decimales: 1,
      unidad: 'g/mol',
      descripcion: 'La masa molar se calcula sumando las masas atómicas',
      placeholder: 'Ej: 18.0',
      feedback: {
        correcto: '¡Correcto! La masa molar del agua es 18 g/mol.',
        incorrecto: 'Recuerda: H=1 y O=16, entonces H2O = 2(1) + 16 = 18',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 8,
  },
  {
    tipo: 'TextInput',
    nombre: 'Campo de Texto',
    descripcion: 'Input de texto con validación y respuestas alternativas',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '✏️',
    configSchema: {},
    ejemploConfig: {
      instruccion: '¿Cuál es el símbolo químico del agua?',
      label: 'Símbolo químico',
      placeholder: 'Ej: H2O',
      respuestaCorrecta: 'H2O',
      respuestasAlternativas: ['agua', 'water'],
      caseSensitive: false,
      descripcion: 'Escribe la fórmula molecular del agua',
      feedback: {
        correcto: '¡Correcto! El agua es H₂O.',
        incorrecto: 'Incorrecto. Pista: tiene 2 hidrógenos y 1 oxígeno.',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 9,
  },
  {
    tipo: 'Hotspot',
    nombre: 'Hotspot',
    descripcion: 'Identificar zonas en imagen con feedback visual',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📍',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Identifica las partes de la célula',
      imagenUrl: '/images/celula.png',
      zonas: [
        {
          id: 'zona1',
          x: 50,
          y: 50,
          ancho: 20,
          alto: 20,
          etiqueta: 'Núcleo',
          descripcion: 'Centro de control de la célula',
        },
      ],
      mostrarEtiquetas: false,
      feedback: { correcto: '¡Correcto!', incorrecto: 'Intenta de nuevo' },
    },
    implementado: true,
    habilitado: true,
    orden: 10,
  },
  {
    tipo: 'Timeline',
    nombre: 'Línea de Tiempo',
    descripcion:
      'Línea temporal interactiva para ordenar eventos cronológicamente',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📅',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Ordena los eventos históricos',
      eventos: [
        {
          id: 'ev1',
          año: 1869,
          titulo: 'Tabla Periódica',
          descripcion: 'Mendeleev crea la tabla periódica',
        },
        {
          id: 'ev2',
          año: 1911,
          titulo: 'Núcleo Atómico',
          descripcion: 'Rutherford descubre el núcleo',
        },
      ],
      modoOrdenar: true,
      orientacion: 'horizontal',
      feedback: { correcto: '¡Correcto!', incorrecto: 'Revisa el orden' },
    },
    implementado: true,
    habilitado: true,
    orden: 11,
  },
  {
    tipo: 'SortingBins',
    nombre: 'Clasificar',
    descripcion: 'Clasificar elementos arrastrándolos a categorías',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🗂️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Clasifica las reacciones según su tipo',
      categorias: [
        { id: 'cat1', nombre: 'Exotérmica', descripcion: 'Libera energía' },
        { id: 'cat2', nombre: 'Endotérmica', descripcion: 'Absorbe energía' },
      ],
      elementos: [
        { id: 'elem1', contenido: 'Combustión', categoriaCorrecta: 'cat1' },
        { id: 'elem2', contenido: 'Fotosíntesis', categoriaCorrecta: 'cat2' },
      ],
      feedback: {
        correcto: '¡Bien clasificado!',
        incorrecto: 'Revisa la clasificación',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 12,
  },
  {
    tipo: 'ScaleBalance',
    nombre: 'Balanza',
    descripcion: 'Balanza interactiva con drag-and-drop para equilibrar',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '⚖️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Equilibra la balanza agregando pesas',
      pesasDisponibles: [
        { id: 'p1', valor: 10, etiqueta: '10g' },
        { id: 'p2', valor: 5, etiqueta: '5g' },
        { id: 'p3', valor: 1, etiqueta: '1g' },
      ],
      pesoObjetivo: 25,
      tolerancia: 0,
      feedback: {
        correcto: '¡Equilibrado!',
        incorrecto: 'La balanza no está equilibrada',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 13,
  },
  {
    tipo: 'PieChart',
    nombre: 'Gráfico Circular',
    descripcion: 'Gráfico circular interactivo con segmentos ajustables',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🥧',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Ajusta el gráfico para mostrar la composición',
      datos: [
        { id: 'd1', etiqueta: 'Carbono', valor: 40, color: '#4A90D9' },
        { id: 'd2', etiqueta: 'Oxígeno', valor: 60, color: '#E74C3C' },
      ],
      esInteractivo: true,
      mostrarPorcentajes: true,
      mostrarLeyenda: true,
      feedback: { correcto: '¡Correcto!', incorrecto: 'Revisa los valores' },
    },
    implementado: true,
    habilitado: true,
    orden: 14,
  },
  {
    tipo: 'BarGraph',
    nombre: 'Gráfico de Barras',
    descripcion: 'Gráfico de barras manipulable con verificación',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📊',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Ajusta las barras para representar los datos',
      datos: [
        { id: 'b1', etiqueta: 'Hierro', valor: 7.8, color: '#3498DB' },
        { id: 'b2', etiqueta: 'Aluminio', valor: 2.7, color: '#E74C3C' },
      ],
      esInteractivo: true,
      min: 0,
      max: 10,
      unidad: 'g/cm³',
      orientacion: 'vertical',
      feedback: { correcto: '¡Correcto!', incorrecto: 'Revisa los valores' },
    },
    implementado: true,
    habilitado: true,
    orden: 15,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 2: MOTRICIDAD FINA (10 componentes)
// Únicos de Mateatletas. Enseñan habilidades físicas a través de gestos táctiles.
// ═══════════════════════════════════════════════════════════════════════════
const MOTRICIDAD_FINA: ComponenteData[] = [
  {
    tipo: 'PinchZoom',
    nombre: 'Pellizcar para Zoom',
    descripcion: 'Pinch in/out - Coordinación bimanual',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🔍',
    configSchema: {},
    ejemploConfig: { imagen: '/celula.png', zoomMin: 0.5, zoomMax: 3 },
    implementado: false,
    habilitado: false,
    orden: 16,
  },
  {
    tipo: 'RotateGesture',
    nombre: 'Rotar con Gestos',
    descripcion: 'Rotar con dos dedos - Manipulación espacial',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🔄',
    configSchema: {},
    ejemploConfig: { modelo3d: '/molecula.glb' },
    implementado: false,
    habilitado: false,
    orden: 17,
  },
  {
    tipo: 'TracePath',
    nombre: 'Trazar Camino',
    descripcion: 'Canvas interactivo para trazar trazos y verificar precisión',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '✍️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Traza el camino indicado siguiendo la línea guía',
      titulo: 'Práctica de Trazo',
      puntos: [
        { x: 50, y: 200 },
        { x: 150, y: 100 },
        { x: 250, y: 200 },
        { x: 350, y: 100 },
      ],
      tolerancia: 20,
      grosorLinea: 3,
      colorGuia: '#3B82F6',
      colorTrazo: '#10B981',
      mostrarGuia: true,
    },
    implementado: true,
    habilitado: true,
    orden: 18,
  },
  {
    tipo: 'PressureControl',
    nombre: 'Control de Presión',
    descripcion: 'Presión variable - Modulación de fuerza',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '💧',
    configSchema: {},
    ejemploConfig: { descripcion: 'Titular ácido gota a gota' },
    implementado: false,
    habilitado: false,
    orden: 19,
  },
  {
    tipo: 'SwipeSequence',
    nombre: 'Secuencia de Swipes',
    descripcion: 'Swipes direccionales - Secuenciación motora',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '👆',
    configSchema: {},
    ejemploConfig: { secuencia: ['arriba', 'derecha', 'abajo', 'izquierda'] },
    implementado: false,
    habilitado: false,
    orden: 20,
  },
  {
    tipo: 'TapRhythm',
    nombre: 'Ritmo de Taps',
    descripcion: 'Taps con timing - Ritmo y coordinación',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🥁',
    configSchema: {},
    ejemploConfig: { bpm: 60, patron: [1, 0, 1, 0, 1, 1, 0, 1] },
    implementado: false,
    habilitado: false,
    orden: 21,
  },
  {
    tipo: 'LongPress',
    nombre: 'Presión Sostenida',
    descripcion: 'Mantener presionado - Inhibición motora',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '⏱️',
    configSchema: {},
    ejemploConfig: { duracionMs: 3000, descripcion: 'Calentar sustancia' },
    implementado: false,
    habilitado: false,
    orden: 22,
  },
  {
    tipo: 'MultiTouch',
    nombre: 'Multi-Touch',
    descripcion: 'Múltiples dedos - Independencia digital',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🖐️',
    configSchema: {},
    ejemploConfig: { teclas: ['do', 're', 'mi', 'fa', 'sol'] },
    implementado: false,
    habilitado: false,
    orden: 23,
  },
  {
    tipo: 'DrawShape',
    nombre: 'Dibujar Forma',
    descripcion: 'Canvas libre para dibujar formas con diferentes herramientas',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🖌️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Dibuja la estructura de Lewis del H2O',
      titulo: 'Dibujo Libre',
      herramientas: ['lapiz', 'linea', 'rectangulo', 'circulo', 'borrador'],
      colores: ['#000000', '#FF0000', '#00FF00', '#0000FF', '#FFFF00'],
      grosorLinea: 3,
      colorFondo: '#FFFFFF',
      anchoCanvas: 400,
      altoCanvas: 300,
    },
    implementado: true,
    habilitado: true,
    orden: 24,
  },
  {
    tipo: 'ScratchReveal',
    nombre: 'Raspar para Revelar',
    descripcion: 'Rascar para revelar - Barrido controlado',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🪙',
    configSchema: {},
    ejemploConfig: { imagenOculta: '/elemento_misterioso.png' },
    implementado: false,
    habilitado: false,
    orden: 25,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 3: SIMULADORES CIENTÍFICOS (25 componentes)
// El corazón de la diferenciación. Nivel Universe Sandbox.
// ═══════════════════════════════════════════════════════════════════════════

// Química (8 simuladores)
const SIMULADORES_QUIMICA: ComponenteData[] = [
  {
    tipo: 'MoleculeBuilder3D',
    nombre: 'Constructor de Moléculas 3D',
    descripcion: 'Geometría molecular, ángulos',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧬',
    configSchema: {},
    ejemploConfig: { molecula: 'H2O', mostrarAngulos: true },
    implementado: false,
    habilitado: false,
    orden: 26,
  },
  {
    tipo: 'ReactionChamber',
    nombre: 'Cámara de Reacción',
    descripcion: 'Cinética, equilibrio, Le Chatelier',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '⚗️',
    configSchema: {},
    ejemploConfig: { reaccion: '2H2 + O2 -> 2H2O' },
    implementado: false,
    habilitado: false,
    orden: 27,
  },
  {
    tipo: 'pHSimulator',
    nombre: 'Simulador de pH',
    descripcion: 'Escala logarítmica, indicadores',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧪',
    configSchema: {},
    ejemploConfig: { sustanciaInicial: 'agua', mostrarIndicador: true },
    implementado: false,
    habilitado: false,
    orden: 28,
  },
  {
    tipo: 'ElectronOrbitals',
    nombre: 'Orbitales Electrónicos',
    descripcion: 'Modelo cuántico simplificado',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '⚛️',
    configSchema: {},
    ejemploConfig: { elemento: 'C', mostrarFormas: true },
    implementado: false,
    habilitado: false,
    orden: 29,
  },
  {
    tipo: 'PeriodicExplorer',
    nombre: 'Explorador de Tabla Periódica',
    descripcion: 'Tendencias periódicas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { propiedad: 'electronegatividad' },
    implementado: false,
    habilitado: false,
    orden: 30,
  },
  {
    tipo: 'StateMatterSim',
    nombre: 'Simulador Estados de Materia',
    descripcion: 'Transiciones de fase, energía',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌡️',
    configSchema: {},
    ejemploConfig: { sustancia: 'agua', temperaturaInicial: 0 },
    implementado: false,
    habilitado: false,
    orden: 31,
  },
  {
    tipo: 'ElectrochemCell',
    nombre: 'Celda Electroquímica',
    descripcion: 'Redox, voltaje, electrólisis',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔋',
    configSchema: {},
    ejemploConfig: { anodo: 'Zn', catodo: 'Cu' },
    implementado: false,
    habilitado: false,
    orden: 32,
  },
  {
    tipo: 'GasLawsSim',
    nombre: 'Simulador Leyes de Gases',
    descripcion: 'PVT, ley ideal, real',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '💨',
    configSchema: {},
    ejemploConfig: { gas: 'ideal', mostrarMoleculas: true },
    implementado: false,
    habilitado: false,
    orden: 33,
  },
];

// Física (9 simuladores)
const SIMULADORES_FISICA: ComponenteData[] = [
  {
    tipo: 'GravitySandbox',
    nombre: 'Sandbox de Gravedad',
    descripcion: 'Gravitación universal, órbitas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌍',
    configSchema: {},
    ejemploConfig: { cuerpos: ['sol', 'tierra', 'luna'] },
    implementado: false,
    habilitado: false,
    orden: 34,
  },
  {
    tipo: 'WaveSimulator',
    nombre: 'Simulador de Ondas',
    descripcion: 'Ondas mecánicas y EM',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌊',
    configSchema: {},
    ejemploConfig: { tipo: 'transversal', frecuencia: 440 },
    implementado: false,
    habilitado: false,
    orden: 35,
  },
  {
    tipo: 'CircuitBuilder',
    nombre: 'Constructor de Circuitos',
    descripcion: 'Ley de Ohm, Kirchhoff',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔌',
    configSchema: {},
    ejemploConfig: { componentes: ['resistencia', 'led', 'bateria'] },
    implementado: false,
    habilitado: false,
    orden: 36,
  },
  {
    tipo: 'ProjectileMotion',
    nombre: 'Movimiento de Proyectil',
    descripcion: 'Cinemática 2D, tiro parabólico',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: { velocidadInicial: 20, angulo: 45 },
    implementado: false,
    habilitado: false,
    orden: 37,
  },
  {
    tipo: 'PendulumLab',
    nombre: 'Laboratorio de Péndulo',
    descripcion: 'Movimiento armónico simple',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🕰️',
    configSchema: {},
    ejemploConfig: { longitud: 1, gravedad: 9.8 },
    implementado: false,
    habilitado: false,
    orden: 38,
  },
  {
    tipo: 'OpticsTable',
    nombre: 'Mesa de Óptica',
    descripcion: 'Reflexión, refracción, lentes',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔭',
    configSchema: {},
    ejemploConfig: { elementos: ['espejo', 'lente', 'prisma'] },
    implementado: false,
    habilitado: false,
    orden: 39,
  },
  {
    tipo: 'ThermodynamicsSim',
    nombre: 'Simulador de Termodinámica',
    descripcion: 'Calor, trabajo, ciclos',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔥',
    configSchema: {},
    ejemploConfig: { ciclo: 'carnot' },
    implementado: false,
    habilitado: false,
    orden: 40,
  },
  {
    tipo: 'FluidSimulator',
    nombre: 'Simulador de Fluidos',
    descripcion: 'Presión, flotación, Bernoulli',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '💧',
    configSchema: {},
    ejemploConfig: { fluido: 'agua', densidad: 1000 },
    implementado: false,
    habilitado: false,
    orden: 41,
  },
  {
    tipo: 'MagnetismLab',
    nombre: 'Laboratorio de Magnetismo',
    descripcion: 'Campos, inducción, Faraday',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧲',
    configSchema: {},
    ejemploConfig: { mostrarLineasCampo: true },
    implementado: false,
    habilitado: false,
    orden: 42,
  },
];

// Biología (5 simuladores)
const SIMULADORES_BIOLOGIA: ComponenteData[] = [
  {
    tipo: 'CellExplorer',
    nombre: 'Explorador Celular',
    descripcion: 'Estructura celular 3D, orgánulos',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔬',
    configSchema: {},
    ejemploConfig: { tipoCelula: 'eucariota', mostrarOrganulos: true },
    implementado: false,
    habilitado: false,
    orden: 43,
  },
  {
    tipo: 'GeneticsLab',
    nombre: 'Laboratorio de Genética',
    descripcion: 'Herencia mendeliana, Punnett',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧬',
    configSchema: {},
    ejemploConfig: { rasgo: 'color_ojos', padres: ['Aa', 'Aa'] },
    implementado: false,
    habilitado: false,
    orden: 44,
  },
  {
    tipo: 'EcosystemSim',
    nombre: 'Simulador de Ecosistema',
    descripcion: 'Poblaciones, cadenas tróficas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌲',
    configSchema: {},
    ejemploConfig: { especies: ['conejo', 'zorro', 'pasto'] },
    implementado: false,
    habilitado: false,
    orden: 45,
  },
  {
    tipo: 'BodySystems',
    nombre: 'Sistemas del Cuerpo',
    descripcion: 'Anatomía interactiva',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '❤️',
    configSchema: {},
    ejemploConfig: { sistema: 'circulatorio' },
    implementado: false,
    habilitado: false,
    orden: 46,
  },
  {
    tipo: 'EvolutionSim',
    nombre: 'Simulador de Evolución',
    descripcion: 'Selección natural, adaptación',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🦎',
    configSchema: {},
    ejemploConfig: { poblacion: 100, generaciones: 50 },
    implementado: false,
    habilitado: false,
    orden: 47,
  },
];

// Matemática (3 simuladores)
const SIMULADORES_MATEMATICA: ComponenteData[] = [
  {
    tipo: 'FunctionGrapher',
    nombre: 'Graficador de Funciones',
    descripcion:
      'Graficador de funciones matemáticas con evaluación interactiva',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '📈',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Grafica la función cuadrática f(x) = x²',
      titulo: 'Graficador de Funciones',
      funcionInicial: 'x^2',
      rangoX: [-10, 10],
      rangoY: [-5, 100],
      mostrarEjes: true,
      mostrarCuadricula: true,
      colorFuncion: '#3B82F6',
      permitirEditar: true,
      mostrarPuntos: true,
    },
    implementado: true,
    habilitado: true,
    orden: 48,
  },
  {
    tipo: 'GeometryCanvas',
    nombre: 'Canvas de Geometría',
    descripcion: 'Construcciones euclidianas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '📐',
    configSchema: {},
    ejemploConfig: { herramientas: ['compas', 'regla'] },
    implementado: false,
    habilitado: false,
    orden: 49,
  },
  {
    tipo: 'StatisticsLab',
    nombre: 'Laboratorio de Estadística',
    descripcion: 'Distribuciones, probabilidad',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🎲',
    configSchema: {},
    ejemploConfig: { experimento: 'lanzar_dado', repeticiones: 1000 },
    implementado: false,
    habilitado: false,
    orden: 50,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 4: EDITORES DE CÓDIGO (10 componentes)
// Para el mundo de Programación. Cada uno adaptado por Casa.
// ═══════════════════════════════════════════════════════════════════════════
const EDITORES_CODIGO: ComponenteData[] = [
  {
    tipo: 'BlockEditor',
    nombre: 'Editor de Bloques',
    descripcion: 'Bloques tipo Scratch para programación visual',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🧩',
    configSchema: {},
    ejemploConfig: { bloques: ['mover', 'girar', 'repetir'] },
    implementado: false,
    habilitado: false,
    orden: 51,
  },
  {
    tipo: 'CodeEditor',
    nombre: 'Editor de Código',
    descripcion: 'Editor Monaco con ejecución, verificación y pistas',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Completa la función',
      lenguaje: 'javascript',
      codigoInicial: 'function suma(a, b) { }',
      permitirEjecucion: true,
      verificarSolucion: true,
    },
    implementado: true,
    habilitado: true,
    orden: 52,
  },
  {
    tipo: 'CodePlayground',
    nombre: 'Playground de Código',
    descripcion: 'Entorno multi-archivo con HTML/CSS/JS y preview en vivo',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🎮',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Crea una página web interactiva',
      archivos: [
        { nombre: 'index.html', lenguaje: 'html', contenido: '<h1>Hola</h1>' },
        {
          nombre: 'styles.css',
          lenguaje: 'css',
          contenido: 'h1 { color: blue; }',
        },
      ],
      mostrarPreview: true,
    },
    implementado: true,
    habilitado: true,
    orden: 53,
  },
  {
    tipo: 'CodeComparison',
    nombre: 'Comparador de Código',
    descripcion: 'Vista diff lado a lado para comparar versiones de código',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '⚖️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Compara las dos versiones',
      lenguaje: 'javascript',
      codigoOriginal: 'var x = 1;',
      codigoModificado: 'const x = 1;',
    },
    implementado: true,
    habilitado: true,
    orden: 54,
  },
  {
    tipo: 'SyntaxHighlight',
    nombre: 'Resaltado de Sintaxis',
    descripcion: 'Visualizador de código con anotaciones y líneas resaltadas',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🎨',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Observa este código',
      lenguaje: 'javascript',
      codigo: 'console.log("Hola");',
      resaltarLineas: [1],
    },
    implementado: true,
    habilitado: true,
    orden: 55,
  },
  {
    tipo: 'SQLPlayground',
    nombre: 'Playground SQL',
    descripcion: 'Queries sobre base de datos simulada con motor SQL integrado',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🗄️',
    configSchema: {},
    ejemploConfig: {
      instruccion:
        'Escribe una consulta para obtener productos con precio mayor a 50',
      tablas: [
        {
          nombre: 'productos',
          columnas: [
            { nombre: 'id', tipo: 'INTEGER', primaryKey: true },
            { nombre: 'nombre', tipo: 'TEXT' },
            { nombre: 'precio', tipo: 'REAL' },
          ],
          datos: [
            { id: 1, nombre: 'Laptop', precio: 899.99 },
            { id: 2, nombre: 'Mouse', precio: 29.99 },
          ],
        },
      ],
      consultaEsperada: 'SELECT * FROM productos WHERE precio > 50',
    },
    implementado: true,
    habilitado: true,
    orden: 56,
  },
  {
    tipo: 'RegexTester',
    nombre: 'Probador de Regex',
    descripcion: 'Expresiones regulares con visualización de matches y grupos',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🔎',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Crea un regex que encuentre todos los correos electrónicos',
      patronInicial: '',
      textosPrueba: [
        'Contacta a juan@ejemplo.com para más info',
        'Email: maria@empresa.org',
      ],
      patronEsperado: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',
      mostrarFlags: true,
      mostrarGrupos: true,
    },
    implementado: true,
    habilitado: true,
    orden: 57,
  },
  {
    tipo: 'AlgorithmViz',
    nombre: 'Visualizador de Algoritmos',
    descripcion:
      'Animación paso a paso de algoritmos de ordenamiento y búsqueda',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🔄',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Observa cómo funciona el algoritmo Bubble Sort',
      algoritmo: 'bubble',
      datosIniciales: [64, 34, 25, 12, 22, 11, 90],
      velocidad: 600,
      mostrarCodigo: true,
    },
    implementado: true,
    habilitado: true,
    orden: 58,
  },
  {
    tipo: 'DataStructureViz',
    nombre: 'Visualizador de Estructuras',
    descripcion:
      'Estructuras de datos animadas: stack, queue, lista enlazada, array',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🌳',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Experimenta con las operaciones de una Pila (Stack)',
      estructura: 'stack',
      datosIniciales: [10, 20, 30],
      capacidadMaxima: 6,
      permitirOperaciones: true,
    },
    implementado: true,
    habilitado: true,
    orden: 59,
  },
  {
    tipo: 'TerminalEmulator',
    nombre: 'Emulador de Terminal',
    descripcion: 'Terminal Linux simulada con sistema de archivos virtual',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '💻',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Practica comandos básicos de Linux',
      prompt: 'estudiante@linux',
      directorioInicial: '/home/usuario',
      objetivoComando: 'ls documentos',
    },
    implementado: true,
    habilitado: true,
    orden: 60,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 5: CREATIVOS (10 componentes)
// Expresión creativa con propósito educativo.
// ═══════════════════════════════════════════════════════════════════════════
const CREATIVOS: ComponenteData[] = [
  {
    tipo: 'PixelArtEditor',
    nombre: 'Editor Pixel Art',
    descripcion: 'Editor pixel art',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🎨',
    configSchema: {},
    ejemploConfig: { tamanio: 32, paleta: ['#ff0000', '#00ff00', '#0000ff'] },
    implementado: false,
    habilitado: false,
    orden: 61,
  },
  {
    tipo: 'VectorDrawing',
    nombre: 'Dibujo Vectorial',
    descripcion: 'Dibujo vectorial',
    categoria: CategoriaComponente.CREATIVO,
    icono: '✏️',
    configSchema: {},
    ejemploConfig: { herramientas: ['linea', 'circulo', 'rectangulo'] },
    implementado: false,
    habilitado: false,
    orden: 62,
  },
  {
    tipo: '3DModeler',
    nombre: 'Modelador 3D',
    descripcion: 'Modelado 3D básico',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🧊',
    configSchema: {},
    ejemploConfig: { primitivas: ['cubo', 'esfera', 'cilindro'] },
    implementado: false,
    habilitado: false,
    orden: 63,
  },
  {
    tipo: 'StoryCreator',
    nombre: 'Creador de Historias',
    descripcion: 'Narrativa con templates',
    categoria: CategoriaComponente.CREATIVO,
    icono: '📖',
    configSchema: {},
    ejemploConfig: { template: 'descubrimiento_cientifico' },
    implementado: false,
    habilitado: false,
    orden: 64,
  },
  {
    tipo: 'PresentationBuilder',
    nombre: 'Constructor de Presentaciones',
    descripcion: 'Crear presentaciones',
    categoria: CategoriaComponente.CREATIVO,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { diapositivas: 5 },
    implementado: false,
    habilitado: false,
    orden: 65,
  },
  {
    tipo: 'MindMapEditor',
    nombre: 'Editor de Mapas Mentales',
    descripcion: 'Mapas mentales',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🧠',
    configSchema: {},
    ejemploConfig: { nodoRaiz: 'Química' },
    implementado: false,
    habilitado: false,
    orden: 66,
  },
  {
    tipo: 'InfoGraphicMaker',
    nombre: 'Creador de Infografías',
    descripcion: 'Crear infografías',
    categoria: CategoriaComponente.CREATIVO,
    icono: '📋',
    configSchema: {},
    ejemploConfig: { template: 'ciclo' },
    implementado: false,
    habilitado: false,
    orden: 67,
  },
  {
    tipo: 'ComicCreator',
    nombre: 'Creador de Cómics',
    descripcion: 'Crear cómics',
    categoria: CategoriaComponente.CREATIVO,
    icono: '💬',
    configSchema: {},
    ejemploConfig: { paneles: 4 },
    implementado: false,
    habilitado: false,
    orden: 68,
  },
  {
    tipo: 'PodcastRecorder',
    nombre: 'Grabador de Podcast',
    descripcion: 'Grabar y editar audio',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🎙️',
    configSchema: {},
    ejemploConfig: { duracionMaxima: 300 },
    implementado: false,
    habilitado: false,
    orden: 69,
  },
  {
    tipo: 'VideoAnnotator',
    nombre: 'Anotador de Video',
    descripcion: 'Anotar sobre video',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🎬',
    configSchema: {},
    ejemploConfig: { videoUrl: '/experimento.mp4' },
    implementado: false,
    habilitado: false,
    orden: 70,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 6: MULTIMEDIA (9 componentes)
// Contenido pasivo pero enriquecido + componentes de presentación
// ═══════════════════════════════════════════════════════════════════════════
const MULTIMEDIA: ComponenteData[] = [
  {
    tipo: 'VideoPlayer',
    nombre: 'Reproductor de Video',
    descripcion: 'Video con interacciones',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '▶️',
    configSchema: {},
    ejemploConfig: {
      url: 'https://youtube.com/watch?v=ejemplo',
      titulo: 'Video de ejemplo',
    },
    implementado: true,
    habilitado: true,
    orden: 71,
  },
  {
    tipo: 'AudioPlayer',
    nombre: 'Reproductor de Audio',
    descripcion: 'Reproductor de audio con transcripción sincronizada',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎵',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Escucha el audio y sigue la transcripción',
      titulo: 'Lección de pronunciación',
      audioUrl: '/audio/lesson.mp3',
      transcripcion: [
        { tiempo: 0, texto: 'Bienvenidos a la lección.' },
        { tiempo: 3, texto: 'Hoy aprenderemos sobre química.' },
      ],
      mostrarVelocidad: true,
      permitirLoop: true,
    },
    implementado: true,
    habilitado: true,
    orden: 72,
  },
  {
    tipo: 'ImageGallery',
    nombre: 'Galería de Imágenes',
    descripcion: 'Galería con zoom, navegación y thumbnails',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🖼️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Explora las imágenes del experimento',
      titulo: 'Galería del laboratorio',
      imagenes: [
        {
          id: 'img1',
          url: '/images/exp1.jpg',
          alt: 'Experimento 1',
          titulo: 'Paso 1',
        },
        {
          id: 'img2',
          url: '/images/exp2.jpg',
          alt: 'Experimento 2',
          titulo: 'Paso 2',
        },
      ],
      disposicion: 'grid',
      autoplay: false,
    },
    implementado: true,
    habilitado: true,
    orden: 73,
  },
  {
    tipo: 'DocumentViewer',
    nombre: 'Visor de Documentos',
    descripcion: 'Visor de PDFs y documentos con navegación y zoom',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '📄',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Lee el siguiente documento',
      titulo: 'Guía de Laboratorio',
      tipo: 'pdf',
      url: '/documentos/guia-laboratorio.pdf',
      paginaInicial: 1,
      permitirDescarga: true,
      permitirZoom: true,
    },
    implementado: true,
    habilitado: true,
    orden: 74,
  },
  {
    tipo: '3DModelViewer',
    nombre: 'Visor de Modelos 3D',
    descripcion: 'Visor de modelos 3D',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🧊',
    configSchema: {},
    ejemploConfig: { url: '/modelo.glb' },
    implementado: false,
    habilitado: false,
    orden: 75,
  },
  {
    tipo: 'InteractivePresentation',
    nombre: 'Presentación Interactiva',
    descripcion: 'Slides con interacción',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '📽️',
    configSchema: {},
    ejemploConfig: {
      slides: [{ titulo: 'Intro', texto: 'Bienvenidos' }],
      tieneAudio: true,
    },
    implementado: false,
    habilitado: false,
    orden: 92,
  },
  {
    tipo: 'NarrationWithTracking',
    nombre: 'Narración con Seguimiento',
    descripcion: 'Audio narra + resalta texto',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🗣️',
    configSchema: {},
    ejemploConfig: { audio: '/narracion.mp3', texto: 'El texto a resaltar...' },
    implementado: false,
    habilitado: false,
    orden: 93,
  },
  {
    tipo: 'StepAnimation',
    nombre: 'Animación por Pasos',
    descripcion: 'Animación secuencial paso a paso con controles de navegación',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎞️',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Observa el proceso paso a paso',
      titulo: 'Proceso de División Celular',
      pasos: [
        {
          id: 'paso1',
          titulo: 'Interfase',
          descripcion: 'La célula crece y duplica su ADN',
          imagenUrl: '/images/interfase.png',
        },
        {
          id: 'paso2',
          titulo: 'Profase',
          descripcion: 'Los cromosomas se condensan y se hacen visibles',
          imagenUrl: '/images/profase.png',
        },
        {
          id: 'paso3',
          titulo: 'Metafase',
          descripcion: 'Los cromosomas se alinean en el centro de la célula',
          imagenUrl: '/images/metafase.png',
        },
      ],
      autoPlay: false,
      velocidad: 2000,
      mostrarIndicadores: true,
      permitirNavegacion: true,
    },
    implementado: true,
    habilitado: true,
    orden: 94,
  },
  {
    tipo: 'Checkpoint',
    nombre: 'Checkpoint',
    descripcion:
      'Punto de verificación con mensaje de logro y animación celebratoria',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🏁',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Has alcanzado un punto de control',
      titulo: 'Checkpoint',
      mensaje:
        '¡Excelente trabajo! Has completado la primera sección del módulo.',
      tipoAnimacion: 'confetti',
      icono: '🎉',
      colorFondo: '#10B981',
      mostrarBotonContinuar: true,
      textoContinuar: 'Continuar al siguiente nivel',
      puntos: 100,
      mostrarPuntos: true,
    },
    implementado: true,
    habilitado: true,
    orden: 95,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 7: EVALUACIÓN (8 componentes)
// Para assessment formativo y sumativo.
// ═══════════════════════════════════════════════════════════════════════════
const EVALUACION: ComponenteData[] = [
  {
    tipo: 'Quiz',
    nombre: 'Quiz',
    descripcion:
      'Cuestionario con preguntas de opción múltiple y verdadero/falso',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Responde las siguientes preguntas',
      titulo: 'Quiz de Química',
      preguntas: [
        {
          id: 'q1',
          tipo: 'opcionMultiple',
          pregunta: '¿Cuál es el símbolo del agua?',
          opciones: ['H2O', 'CO2', 'NaCl'],
          respuestaCorrecta: 'H2O',
        },
        {
          id: 'q2',
          tipo: 'verdaderoFalso',
          pregunta: 'El oro es un metal',
          respuestaCorrecta: true,
        },
      ],
      tiempoLimite: 300,
      permitirReintentar: true,
      feedback: {
        correcto: '¡Excelente! Has aprobado el quiz.',
        incorrecto: 'Necesitas repasar el material.',
      },
    },
    implementado: true,
    habilitado: true,
    orden: 76,
  },
  {
    tipo: 'PracticeMode',
    nombre: 'Modo Práctica',
    descripcion: 'Ejercicios con feedback inmediato',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: { ejercicios: [], sinPuntuacion: true },
    implementado: false,
    habilitado: false,
    orden: 77,
  },
  {
    tipo: 'ChallengeMode',
    nombre: 'Modo Desafío',
    descripcion: 'Ejercicios con tiempo/puntos',
    categoria: CategoriaComponente.EVALUACION,
    icono: '⏱️',
    configSchema: {},
    ejemploConfig: { ejercicios: [], tiempoPorPregunta: 30 },
    implementado: false,
    habilitado: false,
    orden: 78,
  },
  {
    tipo: 'PeerReview',
    nombre: 'Revisión de Pares',
    descripcion: 'Evaluación entre pares',
    categoria: CategoriaComponente.EVALUACION,
    icono: '👥',
    configSchema: {},
    ejemploConfig: { criterios: ['claridad', 'creatividad', 'exactitud'] },
    implementado: false,
    habilitado: false,
    orden: 79,
  },
  {
    tipo: 'Portfolio',
    nombre: 'Portafolio',
    descripcion: 'Recopilación de trabajos',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📁',
    configSchema: {},
    ejemploConfig: { maxTrabajos: 10 },
    implementado: false,
    habilitado: false,
    orden: 80,
  },
  {
    tipo: 'Rubric',
    nombre: 'Rúbrica',
    descripcion: 'Rúbrica de evaluación con criterios y niveles de desempeño',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Evalúa tu trabajo según los siguientes criterios',
      titulo: 'Rúbrica de Evaluación del Proyecto',
      criterios: [
        {
          id: 'crit1',
          nombre: 'Contenido',
          descripcion: 'Calidad y profundidad del contenido presentado',
          peso: 40,
        },
        {
          id: 'crit2',
          nombre: 'Organización',
          descripcion: 'Estructura lógica y coherencia del trabajo',
          peso: 30,
        },
        {
          id: 'crit3',
          nombre: 'Presentación',
          descripcion: 'Claridad visual y formato del trabajo',
          peso: 30,
        },
      ],
      niveles: [
        { id: 'niv1', nombre: 'Excelente', valor: 4, color: '#10B981' },
        { id: 'niv2', nombre: 'Bueno', valor: 3, color: '#3B82F6' },
        { id: 'niv3', nombre: 'Regular', valor: 2, color: '#F59E0B' },
        { id: 'niv4', nombre: 'Necesita mejora', valor: 1, color: '#EF4444' },
      ],
      permitirAutoEvaluacion: true,
      mostrarPuntuacionTotal: true,
    },
    implementado: true,
    habilitado: true,
    orden: 81,
  },
  {
    tipo: 'ProgressTracker',
    nombre: 'Rastreador de Progreso',
    descripcion: 'Visualiza el progreso con barras, objetivos y gamificación',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📊',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Tu progreso en la unidad',
      titulo: 'Progreso del Módulo',
      porcentaje: 75,
      objetivos: [
        { id: 'obj1', nombre: 'Completar lección', completado: true },
        { id: 'obj2', nombre: 'Aprobar quiz', completado: true },
        { id: 'obj3', nombre: 'Entregar proyecto', completado: false },
      ],
      mostrarPorcentaje: true,
      mostrarObjetivos: true,
      colorBarra: '#3B82F6',
      animado: true,
    },
    implementado: true,
    habilitado: true,
    orden: 82,
  },
  {
    tipo: 'BadgeDisplay',
    nombre: 'Mostrar Insignias',
    descripcion: 'Visualizador de insignias y logros obtenidos con animaciones',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🏅',
    configSchema: {},
    ejemploConfig: {
      instruccion: 'Tus logros obtenidos',
      titulo: 'Mis Insignias',
      insignias: [
        {
          id: 'badge1',
          nombre: 'Primer Paso',
          descripcion: 'Completaste tu primera lección',
          icono: '🌟',
          color: '#F59E0B',
          obtenida: true,
          fechaObtencion: '2024-01-15',
        },
        {
          id: 'badge2',
          nombre: 'Explorador',
          descripcion: 'Visitaste todas las secciones',
          icono: '🧭',
          color: '#3B82F6',
          obtenida: true,
          fechaObtencion: '2024-01-20',
        },
        {
          id: 'badge3',
          nombre: 'Maestro',
          descripcion: 'Obtén 100% en un quiz',
          icono: '👑',
          color: '#8B5CF6',
          obtenida: false,
          requisito: 'Completa un quiz con puntuación perfecta',
        },
      ],
      disposicion: 'grid',
      mostrarProgreso: true,
      animarNuevas: true,
    },
    implementado: true,
    habilitado: true,
    orden: 83,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 8: MULTIPLAYER / COLABORATIVO (8 componentes)
// Interacción en tiempo real entre estudiantes.
// ═══════════════════════════════════════════════════════════════════════════
const MULTIPLAYER: ComponenteData[] = [
  {
    tipo: 'SharedWhiteboard',
    nombre: 'Pizarra Compartida',
    descripcion: 'Pizarra colaborativa',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '📋',
    configSchema: {},
    ejemploConfig: { maxParticipantes: 10 },
    implementado: false,
    habilitado: false,
    orden: 84,
  },
  {
    tipo: 'CollaborativeDoc',
    nombre: 'Documento Colaborativo',
    descripcion: 'Documento compartido',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '📝',
    configSchema: {},
    ejemploConfig: { maxParticipantes: 5 },
    implementado: false,
    habilitado: false,
    orden: 85,
  },
  {
    tipo: 'TeamChallenge',
    nombre: 'Desafío por Equipos',
    descripcion: 'Desafío por equipos',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '🏆',
    configSchema: {},
    ejemploConfig: { equipos: 2, jugadoresPorEquipo: 5 },
    implementado: false,
    habilitado: false,
    orden: 86,
  },
  {
    tipo: 'DebateArena',
    nombre: 'Arena de Debate',
    descripcion: 'Debate estructurado',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '🎤',
    configSchema: {},
    ejemploConfig: { tema: 'Energía nuclear', tiempoPorTurno: 120 },
    implementado: false,
    habilitado: false,
    orden: 87,
  },
  {
    tipo: 'PollLive',
    nombre: 'Encuesta en Vivo',
    descripcion: 'Encuestas en tiempo real',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { pregunta: '¿Qué pasará?', opciones: ['A', 'B', 'C'] },
    implementado: false,
    habilitado: false,
    orden: 88,
  },
  {
    tipo: 'BrainstormCloud',
    nombre: 'Nube de Ideas',
    descripcion: 'Nube de ideas colaborativa',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '💭',
    configSchema: {},
    ejemploConfig: { tema: 'Hipótesis' },
    implementado: false,
    habilitado: false,
    orden: 89,
  },
  {
    tipo: 'PeerTutoring',
    nombre: 'Tutoría entre Pares',
    descripcion: 'Sistema de ayuda entre pares',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '🤝',
    configSchema: {},
    ejemploConfig: { emparejamiento: 'automatico' },
    implementado: false,
    habilitado: false,
    orden: 90,
  },
  {
    tipo: 'GroupProject',
    nombre: 'Proyecto Grupal',
    descripcion: 'Gestión de proyecto grupal',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '👥',
    configSchema: {},
    ejemploConfig: { fases: ['planificacion', 'ejecucion', 'presentacion'] },
    implementado: false,
    habilitado: false,
    orden: 91,
  },
];

// Todos los componentes (95 total)
const TODOS_COMPONENTES: ComponenteData[] = [
  ...INTERACTIVOS, // 15
  ...MOTRICIDAD_FINA, // 10
  ...SIMULADORES_QUIMICA, // 8
  ...SIMULADORES_FISICA, // 9
  ...SIMULADORES_BIOLOGIA, // 5
  ...SIMULADORES_MATEMATICA, // 3 = 25 simuladores total
  ...EDITORES_CODIGO, // 10
  ...CREATIVOS, // 10
  ...MULTIMEDIA, // 9
  ...EVALUACION, // 8
  ...MULTIPLAYER, // 8
];

export async function seedComponentesCatalogo(): Promise<void> {
  console.log('🌱 Seeding ComponenteCatalogo...');

  for (const comp of TODOS_COMPONENTES) {
    await prisma.componenteCatalogo.upsert({
      where: { tipo: comp.tipo },
      update: comp,
      create: comp,
    });
  }

  // Estadísticas por categoría
  const porCategoria = {
    INTERACTIVO: INTERACTIVOS.length,
    MOTRICIDAD_FINA: MOTRICIDAD_FINA.length,
    SIMULADOR:
      SIMULADORES_QUIMICA.length +
      SIMULADORES_FISICA.length +
      SIMULADORES_BIOLOGIA.length +
      SIMULADORES_MATEMATICA.length,
    EDITOR_CODIGO: EDITORES_CODIGO.length,
    CREATIVO: CREATIVOS.length,
    MULTIMEDIA: MULTIMEDIA.length,
    EVALUACION: EVALUACION.length,
    MULTIPLAYER: MULTIPLAYER.length,
  };

  const implementados = TODOS_COMPONENTES.filter((c) => c.implementado).length;
  const pendientes = TODOS_COMPONENTES.filter((c) => !c.implementado).length;

  console.log(`✅ Seed completado:`);
  console.log(`   - Total: ${TODOS_COMPONENTES.length} componentes`);
  console.log(`   - Implementados: ${implementados}`);
  console.log(`   - Pendientes: ${pendientes}`);
  console.log(`\n📊 Por categoría:`);
  Object.entries(porCategoria).forEach(([cat, count]) => {
    console.log(`   - ${cat}: ${count}`);
  });
}

// Ejecutar si se llama directamente
seedComponentesCatalogo()
  .catch((e) => {
    console.error('❌ Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
