import { PrismaClient, CategoriaComponente, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

interface ComponenteData {
  tipo: string;
  nombre: string;
  descripcion: string;
  categoria: CategoriaComponente;
  icono: string;
  configSchema: Prisma.InputJsonValue;
  ejemploConfig: Prisma.InputJsonValue;
  implementado: boolean;
  habilitado: boolean;
  orden: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 1: INTERACTIVOS BÁSICOS (15 componentes)
// Los fundamentales. Están en casi todas las actividades.
// ═══════════════════════════════════════════════════════════════════════════
const INTERACTIVOS: ComponenteData[] = [
  {
    tipo: 'DragDropZone',
    nombre: 'Arrastrar y Soltar',
    descripcion: 'Arrastrar elementos a zonas objetivo',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: {
      items: [{ id: '1', contenido: 'Sólido' }],
      zonas: [{ id: 'z1', nombre: 'Estados de materia' }],
    },
    implementado: false,
    habilitado: false,
    orden: 1,
  },
  {
    tipo: 'MatchingPairs',
    nombre: 'Emparejar',
    descripcion: 'Conectar elementos relacionados',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔗',
    configSchema: {},
    ejemploConfig: {
      pares: [
        { izquierda: 'H2O', derecha: 'Agua' },
        { izquierda: 'NaCl', derecha: 'Sal' },
      ],
    },
    implementado: false,
    habilitado: false,
    orden: 2,
  },
  {
    tipo: 'OrderSequence',
    nombre: 'Ordenar Secuencia',
    descripcion: 'Ordenar elementos en secuencia correcta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📋',
    configSchema: {},
    ejemploConfig: {
      elementos: ['Observar', 'Hipótesis', 'Experimentar', 'Concluir'],
    },
    implementado: false,
    habilitado: false,
    orden: 3,
  },
  {
    tipo: 'MultipleChoice',
    nombre: 'Opción Múltiple',
    descripcion: 'Pregunta con múltiples opciones y una respuesta correcta',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔘',
    configSchema: {},
    ejemploConfig: {
      pregunta: '¿Cuánto es 2 + 2?',
      opciones: ['3', '4', '5'],
      respuestaCorrecta: 1,
    },
    implementado: true,
    habilitado: true,
    orden: 4,
  },
  {
    tipo: 'FillBlanks',
    nombre: 'Completar Espacios',
    descripcion: 'Texto con espacios en blanco para completar',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📝',
    configSchema: {},
    ejemploConfig: {
      texto: 'El resultado de {{0}} + {{1}} es {{2}}',
      respuestas: ['2', '3', '5'],
    },
    implementado: true,
    habilitado: true,
    orden: 5,
  },
  {
    tipo: 'Slider',
    nombre: 'Slider',
    descripcion: 'Ajustar valor en rango',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🎚️',
    configSchema: {},
    ejemploConfig: { min: 0, max: 100, valorInicial: 50, paso: 1 },
    implementado: false,
    habilitado: false,
    orden: 6,
  },
  {
    tipo: 'ToggleSwitch',
    nombre: 'Interruptor',
    descripcion: 'On/Off para variables',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔛',
    configSchema: {},
    ejemploConfig: { label: 'Activar catalizador', valorInicial: false },
    implementado: false,
    habilitado: false,
    orden: 7,
  },
  {
    tipo: 'NumberInput',
    nombre: 'Input Numérico',
    descripcion: 'Input numérico con validación',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🔢',
    configSchema: {},
    ejemploConfig: { label: 'Masa molar', min: 0, max: 1000, decimales: 2 },
    implementado: false,
    habilitado: false,
    orden: 8,
  },
  {
    tipo: 'TextInput',
    nombre: 'Campo de Texto',
    descripcion: 'Input de texto libre',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '✏️',
    configSchema: {},
    ejemploConfig: { placeholder: 'Escribe el nombre del compuesto' },
    implementado: false,
    habilitado: false,
    orden: 9,
  },
  {
    tipo: 'Hotspot',
    nombre: 'Hotspot',
    descripcion: 'Identificar zonas en imagen',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📍',
    configSchema: {},
    ejemploConfig: {
      imagen: '/celula.png',
      zonas: [{ x: 50, y: 50, label: 'Núcleo' }],
    },
    implementado: false,
    habilitado: false,
    orden: 10,
  },
  {
    tipo: 'Timeline',
    nombre: 'Línea de Tiempo',
    descripcion: 'Ubicar eventos en línea temporal',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📅',
    configSchema: {},
    ejemploConfig: {
      eventos: [
        { fecha: '1869', descripcion: 'Mendeleev crea la tabla periódica' },
      ],
    },
    implementado: false,
    habilitado: false,
    orden: 11,
  },
  {
    tipo: 'SortingBins',
    nombre: 'Clasificar',
    descripcion: 'Clasificar elementos en múltiples categorías',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🗂️',
    configSchema: {},
    ejemploConfig: {
      categorias: ['Exotérmica', 'Endotérmica'],
      elementos: [{ nombre: 'Combustión', categoria: 'Exotérmica' }],
    },
    implementado: false,
    habilitado: false,
    orden: 12,
  },
  {
    tipo: 'ScaleBalance',
    nombre: 'Balanza',
    descripcion: 'Balanza interactiva para equilibrar',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '⚖️',
    configSchema: {},
    ejemploConfig: { objetivo: 'Equilibrar la ecuación química' },
    implementado: false,
    habilitado: false,
    orden: 13,
  },
  {
    tipo: 'PieChart',
    nombre: 'Gráfico Circular',
    descripcion: 'Gráfico circular interactivo',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '🥧',
    configSchema: {},
    ejemploConfig: {
      datos: [
        { label: 'Carbono', valor: 40 },
        { label: 'Oxígeno', valor: 60 },
      ],
    },
    implementado: false,
    habilitado: false,
    orden: 14,
  },
  {
    tipo: 'BarGraph',
    nombre: 'Gráfico de Barras',
    descripcion: 'Gráfico de barras manipulable',
    categoria: CategoriaComponente.INTERACTIVO,
    icono: '📊',
    configSchema: {},
    ejemploConfig: {
      datos: [
        { label: 'Hierro', valor: 7.8 },
        { label: 'Aluminio', valor: 2.7 },
      ],
    },
    implementado: false,
    habilitado: false,
    orden: 15,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 2: MOTRICIDAD FINA (10 componentes)
// Únicos de Mateatletas. Enseñan habilidades físicas a través de gestos táctiles.
// ═══════════════════════════════════════════════════════════════════════════
const MOTRICIDAD_FINA: ComponenteData[] = [
  {
    tipo: 'PinchZoom',
    nombre: 'Pellizcar para Zoom',
    descripcion: 'Pinch in/out - Coordinación bimanual',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🔍',
    configSchema: {},
    ejemploConfig: { imagen: '/celula.png', zoomMin: 0.5, zoomMax: 3 },
    implementado: false,
    habilitado: false,
    orden: 16,
  },
  {
    tipo: 'RotateGesture',
    nombre: 'Rotar con Gestos',
    descripcion: 'Rotar con dos dedos - Manipulación espacial',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🔄',
    configSchema: {},
    ejemploConfig: { modelo3d: '/molecula.glb' },
    implementado: false,
    habilitado: false,
    orden: 17,
  },
  {
    tipo: 'TracePath',
    nombre: 'Trazar Camino',
    descripcion: 'Seguir trazo con dedo - Control motor fino',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '✍️',
    configSchema: {},
    ejemploConfig: { path: 'M10,10 Q50,50 90,10', tolerancia: 10 },
    implementado: false,
    habilitado: false,
    orden: 18,
  },
  {
    tipo: 'PressureControl',
    nombre: 'Control de Presión',
    descripcion: 'Presión variable - Modulación de fuerza',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '💧',
    configSchema: {},
    ejemploConfig: { descripcion: 'Titular ácido gota a gota' },
    implementado: false,
    habilitado: false,
    orden: 19,
  },
  {
    tipo: 'SwipeSequence',
    nombre: 'Secuencia de Swipes',
    descripcion: 'Swipes direccionales - Secuenciación motora',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '👆',
    configSchema: {},
    ejemploConfig: { secuencia: ['arriba', 'derecha', 'abajo', 'izquierda'] },
    implementado: false,
    habilitado: false,
    orden: 20,
  },
  {
    tipo: 'TapRhythm',
    nombre: 'Ritmo de Taps',
    descripcion: 'Taps con timing - Ritmo y coordinación',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🥁',
    configSchema: {},
    ejemploConfig: { bpm: 60, patron: [1, 0, 1, 0, 1, 1, 0, 1] },
    implementado: false,
    habilitado: false,
    orden: 21,
  },
  {
    tipo: 'LongPress',
    nombre: 'Presión Sostenida',
    descripcion: 'Mantener presionado - Inhibición motora',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '⏱️',
    configSchema: {},
    ejemploConfig: { duracionMs: 3000, descripcion: 'Calentar sustancia' },
    implementado: false,
    habilitado: false,
    orden: 22,
  },
  {
    tipo: 'MultiTouch',
    nombre: 'Multi-Touch',
    descripcion: 'Múltiples dedos - Independencia digital',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🖐️',
    configSchema: {},
    ejemploConfig: { teclas: ['do', 're', 'mi', 'fa', 'sol'] },
    implementado: false,
    habilitado: false,
    orden: 23,
  },
  {
    tipo: 'DrawShape',
    nombre: 'Dibujar Forma',
    descripcion: 'Dibujo libre - Grafomotricidad',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🖌️',
    configSchema: {},
    ejemploConfig: { descripcion: 'Dibuja la estructura de Lewis del H2O' },
    implementado: false,
    habilitado: false,
    orden: 24,
  },
  {
    tipo: 'ScratchReveal',
    nombre: 'Raspar para Revelar',
    descripcion: 'Rascar para revelar - Barrido controlado',
    categoria: CategoriaComponente.MOTRICIDAD_FINA,
    icono: '🪙',
    configSchema: {},
    ejemploConfig: { imagenOculta: '/elemento_misterioso.png' },
    implementado: false,
    habilitado: false,
    orden: 25,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 3: SIMULADORES CIENTÍFICOS (25 componentes)
// El corazón de la diferenciación. Nivel Universe Sandbox.
// ═══════════════════════════════════════════════════════════════════════════

// Química (8 simuladores)
const SIMULADORES_QUIMICA: ComponenteData[] = [
  {
    tipo: 'MoleculeBuilder3D',
    nombre: 'Constructor de Moléculas 3D',
    descripcion: 'Geometría molecular, ángulos',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧬',
    configSchema: {},
    ejemploConfig: { molecula: 'H2O', mostrarAngulos: true },
    implementado: false,
    habilitado: false,
    orden: 26,
  },
  {
    tipo: 'ReactionChamber',
    nombre: 'Cámara de Reacción',
    descripcion: 'Cinética, equilibrio, Le Chatelier',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '⚗️',
    configSchema: {},
    ejemploConfig: { reaccion: '2H2 + O2 -> 2H2O' },
    implementado: false,
    habilitado: false,
    orden: 27,
  },
  {
    tipo: 'pHSimulator',
    nombre: 'Simulador de pH',
    descripcion: 'Escala logarítmica, indicadores',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧪',
    configSchema: {},
    ejemploConfig: { sustanciaInicial: 'agua', mostrarIndicador: true },
    implementado: false,
    habilitado: false,
    orden: 28,
  },
  {
    tipo: 'ElectronOrbitals',
    nombre: 'Orbitales Electrónicos',
    descripcion: 'Modelo cuántico simplificado',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '⚛️',
    configSchema: {},
    ejemploConfig: { elemento: 'C', mostrarFormas: true },
    implementado: false,
    habilitado: false,
    orden: 29,
  },
  {
    tipo: 'PeriodicExplorer',
    nombre: 'Explorador de Tabla Periódica',
    descripcion: 'Tendencias periódicas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { propiedad: 'electronegatividad' },
    implementado: false,
    habilitado: false,
    orden: 30,
  },
  {
    tipo: 'StateMatterSim',
    nombre: 'Simulador Estados de Materia',
    descripcion: 'Transiciones de fase, energía',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌡️',
    configSchema: {},
    ejemploConfig: { sustancia: 'agua', temperaturaInicial: 0 },
    implementado: false,
    habilitado: false,
    orden: 31,
  },
  {
    tipo: 'ElectrochemCell',
    nombre: 'Celda Electroquímica',
    descripcion: 'Redox, voltaje, electrólisis',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔋',
    configSchema: {},
    ejemploConfig: { anodo: 'Zn', catodo: 'Cu' },
    implementado: false,
    habilitado: false,
    orden: 32,
  },
  {
    tipo: 'GasLawsSim',
    nombre: 'Simulador Leyes de Gases',
    descripcion: 'PVT, ley ideal, real',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '💨',
    configSchema: {},
    ejemploConfig: { gas: 'ideal', mostrarMoleculas: true },
    implementado: false,
    habilitado: false,
    orden: 33,
  },
];

// Física (9 simuladores)
const SIMULADORES_FISICA: ComponenteData[] = [
  {
    tipo: 'GravitySandbox',
    nombre: 'Sandbox de Gravedad',
    descripcion: 'Gravitación universal, órbitas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌍',
    configSchema: {},
    ejemploConfig: { cuerpos: ['sol', 'tierra', 'luna'] },
    implementado: false,
    habilitado: false,
    orden: 34,
  },
  {
    tipo: 'WaveSimulator',
    nombre: 'Simulador de Ondas',
    descripcion: 'Ondas mecánicas y EM',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌊',
    configSchema: {},
    ejemploConfig: { tipo: 'transversal', frecuencia: 440 },
    implementado: false,
    habilitado: false,
    orden: 35,
  },
  {
    tipo: 'CircuitBuilder',
    nombre: 'Constructor de Circuitos',
    descripcion: 'Ley de Ohm, Kirchhoff',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔌',
    configSchema: {},
    ejemploConfig: { componentes: ['resistencia', 'led', 'bateria'] },
    implementado: false,
    habilitado: false,
    orden: 36,
  },
  {
    tipo: 'ProjectileMotion',
    nombre: 'Movimiento de Proyectil',
    descripcion: 'Cinemática 2D, tiro parabólico',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: { velocidadInicial: 20, angulo: 45 },
    implementado: false,
    habilitado: false,
    orden: 37,
  },
  {
    tipo: 'PendulumLab',
    nombre: 'Laboratorio de Péndulo',
    descripcion: 'Movimiento armónico simple',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🕰️',
    configSchema: {},
    ejemploConfig: { longitud: 1, gravedad: 9.8 },
    implementado: false,
    habilitado: false,
    orden: 38,
  },
  {
    tipo: 'OpticsTable',
    nombre: 'Mesa de Óptica',
    descripcion: 'Reflexión, refracción, lentes',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔭',
    configSchema: {},
    ejemploConfig: { elementos: ['espejo', 'lente', 'prisma'] },
    implementado: false,
    habilitado: false,
    orden: 39,
  },
  {
    tipo: 'ThermodynamicsSim',
    nombre: 'Simulador de Termodinámica',
    descripcion: 'Calor, trabajo, ciclos',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔥',
    configSchema: {},
    ejemploConfig: { ciclo: 'carnot' },
    implementado: false,
    habilitado: false,
    orden: 40,
  },
  {
    tipo: 'FluidSimulator',
    nombre: 'Simulador de Fluidos',
    descripcion: 'Presión, flotación, Bernoulli',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '💧',
    configSchema: {},
    ejemploConfig: { fluido: 'agua', densidad: 1000 },
    implementado: false,
    habilitado: false,
    orden: 41,
  },
  {
    tipo: 'MagnetismLab',
    nombre: 'Laboratorio de Magnetismo',
    descripcion: 'Campos, inducción, Faraday',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧲',
    configSchema: {},
    ejemploConfig: { mostrarLineasCampo: true },
    implementado: false,
    habilitado: false,
    orden: 42,
  },
];

// Biología (5 simuladores)
const SIMULADORES_BIOLOGIA: ComponenteData[] = [
  {
    tipo: 'CellExplorer',
    nombre: 'Explorador Celular',
    descripcion: 'Estructura celular 3D, orgánulos',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🔬',
    configSchema: {},
    ejemploConfig: { tipoCelula: 'eucariota', mostrarOrganulos: true },
    implementado: false,
    habilitado: false,
    orden: 43,
  },
  {
    tipo: 'GeneticsLab',
    nombre: 'Laboratorio de Genética',
    descripcion: 'Herencia mendeliana, Punnett',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🧬',
    configSchema: {},
    ejemploConfig: { rasgo: 'color_ojos', padres: ['Aa', 'Aa'] },
    implementado: false,
    habilitado: false,
    orden: 44,
  },
  {
    tipo: 'EcosystemSim',
    nombre: 'Simulador de Ecosistema',
    descripcion: 'Poblaciones, cadenas tróficas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🌲',
    configSchema: {},
    ejemploConfig: { especies: ['conejo', 'zorro', 'pasto'] },
    implementado: false,
    habilitado: false,
    orden: 45,
  },
  {
    tipo: 'BodySystems',
    nombre: 'Sistemas del Cuerpo',
    descripcion: 'Anatomía interactiva',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '❤️',
    configSchema: {},
    ejemploConfig: { sistema: 'circulatorio' },
    implementado: false,
    habilitado: false,
    orden: 46,
  },
  {
    tipo: 'EvolutionSim',
    nombre: 'Simulador de Evolución',
    descripcion: 'Selección natural, adaptación',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🦎',
    configSchema: {},
    ejemploConfig: { poblacion: 100, generaciones: 50 },
    implementado: false,
    habilitado: false,
    orden: 47,
  },
];

// Matemática (3 simuladores)
const SIMULADORES_MATEMATICA: ComponenteData[] = [
  {
    tipo: 'FunctionGrapher',
    nombre: 'Graficador de Funciones',
    descripcion: 'Funciones 2D y 3D',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '📈',
    configSchema: {},
    ejemploConfig: { funcion: 'x^2', rango: [-10, 10] },
    implementado: false,
    habilitado: false,
    orden: 48,
  },
  {
    tipo: 'GeometryCanvas',
    nombre: 'Canvas de Geometría',
    descripcion: 'Construcciones euclidianas',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '📐',
    configSchema: {},
    ejemploConfig: { herramientas: ['compas', 'regla'] },
    implementado: false,
    habilitado: false,
    orden: 49,
  },
  {
    tipo: 'StatisticsLab',
    nombre: 'Laboratorio de Estadística',
    descripcion: 'Distribuciones, probabilidad',
    categoria: CategoriaComponente.SIMULADOR,
    icono: '🎲',
    configSchema: {},
    ejemploConfig: { experimento: 'lanzar_dado', repeticiones: 1000 },
    implementado: false,
    habilitado: false,
    orden: 50,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 4: EDITORES DE CÓDIGO (10 componentes)
// Para el mundo de Programación. Cada uno adaptado por Casa.
// ═══════════════════════════════════════════════════════════════════════════
const EDITORES_CODIGO: ComponenteData[] = [
  {
    tipo: 'BlockEditor',
    nombre: 'Editor de Bloques',
    descripcion: 'Bloques tipo Scratch',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🧩',
    configSchema: {},
    ejemploConfig: { bloques: ['mover', 'girar', 'repetir'] },
    implementado: false,
    habilitado: false,
    orden: 51,
  },
  {
    tipo: 'PythonEditor',
    nombre: 'Editor Python',
    descripcion: 'Editor Python con ejecución',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🐍',
    configSchema: {},
    ejemploConfig: { codigoInicial: 'print("Hola mundo")' },
    implementado: false,
    habilitado: false,
    orden: 52,
  },
  {
    tipo: 'LuaEditor',
    nombre: 'Editor Lua',
    descripcion: 'Editor Lua para Roblox',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🎮',
    configSchema: {},
    ejemploConfig: { codigoInicial: 'print("Hola Roblox")' },
    implementado: false,
    habilitado: false,
    orden: 53,
  },
  {
    tipo: 'JavaScriptEditor',
    nombre: 'Editor JavaScript',
    descripcion: 'Editor JS con ejecución',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '⚡',
    configSchema: {},
    ejemploConfig: { codigoInicial: 'console.log("Hola JS")' },
    implementado: false,
    habilitado: false,
    orden: 54,
  },
  {
    tipo: 'HTMLCSSEditor',
    nombre: 'Editor HTML/CSS',
    descripcion: 'Editor web dual',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🌐',
    configSchema: {},
    ejemploConfig: { html: '<h1>Hola</h1>', css: 'h1 { color: blue; }' },
    implementado: false,
    habilitado: false,
    orden: 55,
  },
  {
    tipo: 'SQLPlayground',
    nombre: 'Playground SQL',
    descripcion: 'Queries sobre DB simulada',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🗄️',
    configSchema: {},
    ejemploConfig: { tablas: ['usuarios', 'productos'] },
    implementado: false,
    habilitado: false,
    orden: 56,
  },
  {
    tipo: 'RegexTester',
    nombre: 'Probador de Regex',
    descripcion: 'Expresiones regulares',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🔎',
    configSchema: {},
    ejemploConfig: { patron: '[a-z]+', texto: 'hola mundo' },
    implementado: false,
    habilitado: false,
    orden: 57,
  },
  {
    tipo: 'AlgorithmViz',
    nombre: 'Visualizador de Algoritmos',
    descripcion: 'Visualización de algoritmos',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🔄',
    configSchema: {},
    ejemploConfig: { algoritmo: 'bubble_sort', datos: [5, 3, 8, 1, 2] },
    implementado: false,
    habilitado: false,
    orden: 58,
  },
  {
    tipo: 'DataStructureViz',
    nombre: 'Visualizador de Estructuras',
    descripcion: 'Estructuras de datos animadas',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '🌳',
    configSchema: {},
    ejemploConfig: { estructura: 'arbol_binario' },
    implementado: false,
    habilitado: false,
    orden: 59,
  },
  {
    tipo: 'TerminalEmulator',
    nombre: 'Emulador de Terminal',
    descripcion: 'Terminal simulada',
    categoria: CategoriaComponente.EDITOR_CODIGO,
    icono: '💻',
    configSchema: {},
    ejemploConfig: { comandosDisponibles: ['ls', 'cd', 'cat'] },
    implementado: false,
    habilitado: false,
    orden: 60,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 5: CREATIVOS (10 componentes)
// Expresión creativa con propósito educativo.
// ═══════════════════════════════════════════════════════════════════════════
const CREATIVOS: ComponenteData[] = [
  {
    tipo: 'PixelArtEditor',
    nombre: 'Editor Pixel Art',
    descripcion: 'Editor pixel art',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🎨',
    configSchema: {},
    ejemploConfig: { tamanio: 32, paleta: ['#ff0000', '#00ff00', '#0000ff'] },
    implementado: false,
    habilitado: false,
    orden: 61,
  },
  {
    tipo: 'VectorDrawing',
    nombre: 'Dibujo Vectorial',
    descripcion: 'Dibujo vectorial',
    categoria: CategoriaComponente.CREATIVO,
    icono: '✏️',
    configSchema: {},
    ejemploConfig: { herramientas: ['linea', 'circulo', 'rectangulo'] },
    implementado: false,
    habilitado: false,
    orden: 62,
  },
  {
    tipo: '3DModeler',
    nombre: 'Modelador 3D',
    descripcion: 'Modelado 3D básico',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🧊',
    configSchema: {},
    ejemploConfig: { primitivas: ['cubo', 'esfera', 'cilindro'] },
    implementado: false,
    habilitado: false,
    orden: 63,
  },
  {
    tipo: 'StoryCreator',
    nombre: 'Creador de Historias',
    descripcion: 'Narrativa con templates',
    categoria: CategoriaComponente.CREATIVO,
    icono: '📖',
    configSchema: {},
    ejemploConfig: { template: 'descubrimiento_cientifico' },
    implementado: false,
    habilitado: false,
    orden: 64,
  },
  {
    tipo: 'PresentationBuilder',
    nombre: 'Constructor de Presentaciones',
    descripcion: 'Crear presentaciones',
    categoria: CategoriaComponente.CREATIVO,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { diapositivas: 5 },
    implementado: false,
    habilitado: false,
    orden: 65,
  },
  {
    tipo: 'MindMapEditor',
    nombre: 'Editor de Mapas Mentales',
    descripcion: 'Mapas mentales',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🧠',
    configSchema: {},
    ejemploConfig: { nodoRaiz: 'Química' },
    implementado: false,
    habilitado: false,
    orden: 66,
  },
  {
    tipo: 'InfoGraphicMaker',
    nombre: 'Creador de Infografías',
    descripcion: 'Crear infografías',
    categoria: CategoriaComponente.CREATIVO,
    icono: '📋',
    configSchema: {},
    ejemploConfig: { template: 'ciclo' },
    implementado: false,
    habilitado: false,
    orden: 67,
  },
  {
    tipo: 'ComicCreator',
    nombre: 'Creador de Cómics',
    descripcion: 'Crear cómics',
    categoria: CategoriaComponente.CREATIVO,
    icono: '💬',
    configSchema: {},
    ejemploConfig: { paneles: 4 },
    implementado: false,
    habilitado: false,
    orden: 68,
  },
  {
    tipo: 'PodcastRecorder',
    nombre: 'Grabador de Podcast',
    descripcion: 'Grabar y editar audio',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🎙️',
    configSchema: {},
    ejemploConfig: { duracionMaxima: 300 },
    implementado: false,
    habilitado: false,
    orden: 69,
  },
  {
    tipo: 'VideoAnnotator',
    nombre: 'Anotador de Video',
    descripcion: 'Anotar sobre video',
    categoria: CategoriaComponente.CREATIVO,
    icono: '🎬',
    configSchema: {},
    ejemploConfig: { videoUrl: '/experimento.mp4' },
    implementado: false,
    habilitado: false,
    orden: 70,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 6: MULTIMEDIA (9 componentes)
// Contenido pasivo pero enriquecido + componentes de presentación
// ═══════════════════════════════════════════════════════════════════════════
const MULTIMEDIA: ComponenteData[] = [
  {
    tipo: 'VideoPlayer',
    nombre: 'Reproductor de Video',
    descripcion: 'Video con interacciones',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '▶️',
    configSchema: {},
    ejemploConfig: {
      url: 'https://youtube.com/watch?v=ejemplo',
      titulo: 'Video de ejemplo',
    },
    implementado: true,
    habilitado: true,
    orden: 71,
  },
  {
    tipo: 'AudioPlayer',
    nombre: 'Reproductor de Audio',
    descripcion: 'Audio con transcripción',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎵',
    configSchema: {},
    ejemploConfig: { url: '/audio.mp3', transcripcion: 'Texto del audio...' },
    implementado: false,
    habilitado: false,
    orden: 72,
  },
  {
    tipo: 'ImageGallery',
    nombre: 'Galería de Imágenes',
    descripcion: 'Galería con zoom y anotaciones',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🖼️',
    configSchema: {},
    ejemploConfig: { imagenes: ['/img1.png', '/img2.png'] },
    implementado: false,
    habilitado: false,
    orden: 73,
  },
  {
    tipo: 'DocumentViewer',
    nombre: 'Visor de Documentos',
    descripcion: 'PDFs y docs interactivos',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '📄',
    configSchema: {},
    ejemploConfig: { url: '/documento.pdf' },
    implementado: false,
    habilitado: false,
    orden: 74,
  },
  {
    tipo: '3DModelViewer',
    nombre: 'Visor de Modelos 3D',
    descripcion: 'Visor de modelos 3D',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🧊',
    configSchema: {},
    ejemploConfig: { url: '/modelo.glb' },
    implementado: false,
    habilitado: false,
    orden: 75,
  },
  {
    tipo: 'InteractivePresentation',
    nombre: 'Presentación Interactiva',
    descripcion: 'Slides con interacción',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '📽️',
    configSchema: {},
    ejemploConfig: {
      slides: [{ titulo: 'Intro', texto: 'Bienvenidos' }],
      tieneAudio: true,
    },
    implementado: false,
    habilitado: false,
    orden: 92,
  },
  {
    tipo: 'NarrationWithTracking',
    nombre: 'Narración con Seguimiento',
    descripcion: 'Audio narra + resalta texto',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🗣️',
    configSchema: {},
    ejemploConfig: { audio: '/narracion.mp3', texto: 'El texto a resaltar...' },
    implementado: false,
    habilitado: false,
    orden: 93,
  },
  {
    tipo: 'StepAnimation',
    nombre: 'Animación por Pasos',
    descripcion: 'Animación paso a paso',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🎞️',
    configSchema: {},
    ejemploConfig: { pasos: ['Paso 1', 'Paso 2', 'Paso 3'] },
    implementado: false,
    habilitado: false,
    orden: 94,
  },
  {
    tipo: 'Checkpoint',
    nombre: 'Checkpoint',
    descripcion: 'Mensaje de logro + animación',
    categoria: CategoriaComponente.MULTIMEDIA,
    icono: '🏁',
    configSchema: {},
    ejemploConfig: {
      mensaje: '¡Completaste la sección!',
      animacion: 'celebracionSimple',
    },
    implementado: false,
    habilitado: false,
    orden: 95,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 7: EVALUACIÓN (8 componentes)
// Para assessment formativo y sumativo.
// ═══════════════════════════════════════════════════════════════════════════
const EVALUACION: ComponenteData[] = [
  {
    tipo: 'Quiz',
    nombre: 'Quiz',
    descripcion: 'Cuestionario tradicional',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📝',
    configSchema: {},
    ejemploConfig: { preguntas: [], tiempoLimite: 600 },
    implementado: false,
    habilitado: false,
    orden: 76,
  },
  {
    tipo: 'PracticeMode',
    nombre: 'Modo Práctica',
    descripcion: 'Ejercicios con feedback inmediato',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🎯',
    configSchema: {},
    ejemploConfig: { ejercicios: [], sinPuntuacion: true },
    implementado: false,
    habilitado: false,
    orden: 77,
  },
  {
    tipo: 'ChallengeMode',
    nombre: 'Modo Desafío',
    descripcion: 'Ejercicios con tiempo/puntos',
    categoria: CategoriaComponente.EVALUACION,
    icono: '⏱️',
    configSchema: {},
    ejemploConfig: { ejercicios: [], tiempoPorPregunta: 30 },
    implementado: false,
    habilitado: false,
    orden: 78,
  },
  {
    tipo: 'PeerReview',
    nombre: 'Revisión de Pares',
    descripcion: 'Evaluación entre pares',
    categoria: CategoriaComponente.EVALUACION,
    icono: '👥',
    configSchema: {},
    ejemploConfig: { criterios: ['claridad', 'creatividad', 'exactitud'] },
    implementado: false,
    habilitado: false,
    orden: 79,
  },
  {
    tipo: 'Portfolio',
    nombre: 'Portafolio',
    descripcion: 'Recopilación de trabajos',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📁',
    configSchema: {},
    ejemploConfig: { maxTrabajos: 10 },
    implementado: false,
    habilitado: false,
    orden: 80,
  },
  {
    tipo: 'Rubric',
    nombre: 'Rúbrica',
    descripcion: 'Rúbricas de evaluación',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📋',
    configSchema: {},
    ejemploConfig: { criterios: [], niveles: 4 },
    implementado: false,
    habilitado: false,
    orden: 81,
  },
  {
    tipo: 'ProgressTracker',
    nombre: 'Rastreador de Progreso',
    descripcion: 'Visualización de progreso',
    categoria: CategoriaComponente.EVALUACION,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { objetivos: [] },
    implementado: false,
    habilitado: false,
    orden: 82,
  },
  {
    tipo: 'BadgeDisplay',
    nombre: 'Mostrar Insignias',
    descripcion: 'Mostrar logros',
    categoria: CategoriaComponente.EVALUACION,
    icono: '🏅',
    configSchema: {},
    ejemploConfig: { badges: [] },
    implementado: false,
    habilitado: false,
    orden: 83,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORÍA 8: MULTIPLAYER / COLABORATIVO (8 componentes)
// Interacción en tiempo real entre estudiantes.
// ═══════════════════════════════════════════════════════════════════════════
const MULTIPLAYER: ComponenteData[] = [
  {
    tipo: 'SharedWhiteboard',
    nombre: 'Pizarra Compartida',
    descripcion: 'Pizarra colaborativa',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '📋',
    configSchema: {},
    ejemploConfig: { maxParticipantes: 10 },
    implementado: false,
    habilitado: false,
    orden: 84,
  },
  {
    tipo: 'CollaborativeDoc',
    nombre: 'Documento Colaborativo',
    descripcion: 'Documento compartido',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '📝',
    configSchema: {},
    ejemploConfig: { maxParticipantes: 5 },
    implementado: false,
    habilitado: false,
    orden: 85,
  },
  {
    tipo: 'TeamChallenge',
    nombre: 'Desafío por Equipos',
    descripcion: 'Desafío por equipos',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '🏆',
    configSchema: {},
    ejemploConfig: { equipos: 2, jugadoresPorEquipo: 5 },
    implementado: false,
    habilitado: false,
    orden: 86,
  },
  {
    tipo: 'DebateArena',
    nombre: 'Arena de Debate',
    descripcion: 'Debate estructurado',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '🎤',
    configSchema: {},
    ejemploConfig: { tema: 'Energía nuclear', tiempoPorTurno: 120 },
    implementado: false,
    habilitado: false,
    orden: 87,
  },
  {
    tipo: 'PollLive',
    nombre: 'Encuesta en Vivo',
    descripcion: 'Encuestas en tiempo real',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '📊',
    configSchema: {},
    ejemploConfig: { pregunta: '¿Qué pasará?', opciones: ['A', 'B', 'C'] },
    implementado: false,
    habilitado: false,
    orden: 88,
  },
  {
    tipo: 'BrainstormCloud',
    nombre: 'Nube de Ideas',
    descripcion: 'Nube de ideas colaborativa',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '💭',
    configSchema: {},
    ejemploConfig: { tema: 'Hipótesis' },
    implementado: false,
    habilitado: false,
    orden: 89,
  },
  {
    tipo: 'PeerTutoring',
    nombre: 'Tutoría entre Pares',
    descripcion: 'Sistema de ayuda entre pares',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '🤝',
    configSchema: {},
    ejemploConfig: { emparejamiento: 'automatico' },
    implementado: false,
    habilitado: false,
    orden: 90,
  },
  {
    tipo: 'GroupProject',
    nombre: 'Proyecto Grupal',
    descripcion: 'Gestión de proyecto grupal',
    categoria: CategoriaComponente.MULTIPLAYER,
    icono: '👥',
    configSchema: {},
    ejemploConfig: { fases: ['planificacion', 'ejecucion', 'presentacion'] },
    implementado: false,
    habilitado: false,
    orden: 91,
  },
];

// Todos los componentes (95 total)
const TODOS_COMPONENTES: ComponenteData[] = [
  ...INTERACTIVOS, // 15
  ...MOTRICIDAD_FINA, // 10
  ...SIMULADORES_QUIMICA, // 8
  ...SIMULADORES_FISICA, // 9
  ...SIMULADORES_BIOLOGIA, // 5
  ...SIMULADORES_MATEMATICA, // 3 = 25 simuladores total
  ...EDITORES_CODIGO, // 10
  ...CREATIVOS, // 10
  ...MULTIMEDIA, // 9
  ...EVALUACION, // 8
  ...MULTIPLAYER, // 8
];

export async function seedComponentesCatalogo(): Promise<void> {
  console.log('🌱 Seeding ComponenteCatalogo...');

  for (const comp of TODOS_COMPONENTES) {
    await prisma.componenteCatalogo.upsert({
      where: { tipo: comp.tipo },
      update: comp,
      create: comp,
    });
  }

  // Estadísticas por categoría
  const porCategoria = {
    INTERACTIVO: INTERACTIVOS.length,
    MOTRICIDAD_FINA: MOTRICIDAD_FINA.length,
    SIMULADOR:
      SIMULADORES_QUIMICA.length +
      SIMULADORES_FISICA.length +
      SIMULADORES_BIOLOGIA.length +
      SIMULADORES_MATEMATICA.length,
    EDITOR_CODIGO: EDITORES_CODIGO.length,
    CREATIVO: CREATIVOS.length,
    MULTIMEDIA: MULTIMEDIA.length,
    EVALUACION: EVALUACION.length,
    MULTIPLAYER: MULTIPLAYER.length,
  };

  const implementados = TODOS_COMPONENTES.filter((c) => c.implementado).length;
  const pendientes = TODOS_COMPONENTES.filter((c) => !c.implementado).length;

  console.log(`✅ Seed completado:`);
  console.log(`   - Total: ${TODOS_COMPONENTES.length} componentes`);
  console.log(`   - Implementados: ${implementados}`);
  console.log(`   - Pendientes: ${pendientes}`);
  console.log(`\n📊 Por categoría:`);
  Object.entries(porCategoria).forEach(([cat, count]) => {
    console.log(`   - ${cat}: ${count}`);
  });
}

// Ejecutar si se llama directamente
seedComponentesCatalogo()
  .catch((e) => {
    console.error('❌ Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
